name: Build and deploy to Azure Web App

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
    
    - name: Create deployment package
      run: |
        mkdir -p deployment
        cp *.html deployment/
        cp -r assets deployment/ 2>/dev/null || true
        cp -r css deployment/ 2>/dev/null || true
        cp -r js deployment/ 2>/dev/null || true
        cp -r images deployment/ 2>/dev/null || true
        ls -la deployment/
    
    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'photosafari'  # Replace with your Azure Web App name
        slot-name: 'production'
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: './deployment'
